### PR TITLE
Fixed share as image menu

### LINKED ISSUE #47: Fix share document as image
Currently exporting a markdown document as image just exports the visible part. Resolving this should export the whole document as image. Also the image currently contains a lot of whitespace on bottom (see image), which should be gone too. 

<table><tr><td></td></tr></table>

### PR DESCRIPTION
**Pull request by jvretamero**
Fix #47

### CODE REVIEW

File: app/src/main/java/net/gsantner/markor/activity/PreviewActivity.java [hunk 1]
```diff
@@ -60,6 +61,11 @@
     @Override
     protected void onCreate(Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);
+
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
+            WebView.enableSlowWholeDocumentDraw();
```
Comment (gsantner) [inline app/src/main/java/net/gsantner/markor/activity/PreviewActivity.java]: can this be toggled before picture creation too?

Comment (jvretamero) [reply app/src/main/java/net/gsantner/markor/activity/PreviewActivity.java]: If I understood your question correctly, there is no need to toogle this configuration, because the [documentation](https://developer.android.com/reference/android/webkit/WebView.html#enableSlowWholeDocumentDraw()) says _"This method should be called before any WebViews are created."_ and there is no method like _"disableSlowWholeDocumentDraw()"_.

Comment (gsantner) [reply app/src/main/java/net/gsantner/markor/activity/PreviewActivity.java]: does it make a big speed impact when using this in markor?

File: app/src/main/res/layout/preview__activity.xml [hunk 2]
```diff
@@ -1,16 +1,21 @@
...
+    android:orientation="vertical">
 
     <include
         android:id="@+id/toolbar"
-        layout="@layout/toolbar"/>
+        layout="@layout/toolbar" />
 
-    <WebView
-        android:id="@+id/preview__activity__webview"
+    <ScrollView
```
Comment (gsantner) [inline app/src/main/res/layout/preview__activity.xml]: Does scrolling work on older devices (minApi) too? Horizontal and vertical? <https://stackoverflow.com/questions/9718245/webview-in-scrollview>

File: app/src/main/java/net/gsantner/markor/activity/PreviewActivity.java (hunk 1 above)
Comment (jvretamero) [reply app/src/main/java/net/gsantner/markor/activity/PreviewActivity.java]: No

File: app/src/main/res/layout/preview__activity.xml (hunk 2 above)
Comment (jvretamero) [reply app/src/main/res/layout/preview__activity.xml]: I just did other tests varying the implementation and also the devices, so:

1. It works with the current minApi (16)
2. As you can see, I did two commits, the ScrollView was needed to make the first implementation work. I have tested the pull request's current implementation and the ScrollView is not needed anymore

Do I create another commit without the ScrollView?

Comment (gsantner) [reply app/src/main/res/layout/preview__activity.xml]: yep, that may create bugs in some cases

Comment (jvretamero) [reply app/src/main/res/layout/preview__activity.xml]: Done

**Comment by gsantner** [comment]
🎉 thanks
