### PR TITLE
Fixed #45, replaced Uri.fromFile with FileProvider

### LINKED ISSUE #45: Crash at net.gsantner.markor.activity.PreviewActivity.shareStream (PreviewActivity.java:177)
Paste from google developer console

```
vor 33 Minuten in der App-Version 4
Google Pixel (sailfish), 4096MB RAM, Android 8.0
android.os.FileUriExposedException: 
 
  at android.os.StrictMode.onFileUriExposed (StrictMode.java:1958)
 
  at android.net.Uri.checkFileUriExposed (Uri.java:2348)
 
  at android.content.ClipData.prepareToLeaveProcess (ClipData.java:941)
 
  at android.content.Intent.prepareToLeaveProcess (Intent.java:9735)
 
  at android.content.Intent.prepareToLeaveProcess (Intent.java:9741)
 
  at android.content.Intent.prepareToLeaveProcess (Intent.java:9720)
 
  at android.app.Instrumentation.execStartActivity (Instrumentation.java:1609)
 
  at android.app.Activity.startActivityForResult (Activity.java:4472)
 
  at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult (BaseFragmentActivityApi16.java:54)
 
  at android.support.v4.app.FragmentActivity.startActivityForResult (FragmentActivity.java:65)
 
  at android.app.Activity.startActivityForResult (Activity.java:4430)
 
  at android.support.v4.app.FragmentActivity.startActivityForResult (FragmentActivity.java:711)
 
  at android.app.Activity.startActivity (Activity.java:4791)
 
  at android.app.Activity.startActivity (Activity.java:4759)
 
  at net.gsantner.markor.activity.PreviewActivity.shareStream (PreviewActivity.java:177)
 
  at net.gsantner.markor.activity.PreviewActivity.onOptionsItemSelected (PreviewActivity.java:146)
 
  at android.app.Activity.onMenuItemSelected (Activity.java:3435)
 
  at android.support.v4.app.FragmentActivity.onMenuItemSelected (FragmentActivity.java:361)
 
  at android.support.v7.app.AppCompatActivity.onMenuItemSelected (AppCompatActivity.java:195)
 
  at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected (WindowCallbackWrapper.java:108)
 
  at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected (WindowCallbackWrapper.java:108)
 
  at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick (ToolbarActionBar.java:65)
 
  at android.support.v7.widget.Toolbar$1.onMenuItemClick (Toolbar.java:202)
 
  at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected (ActionMenuView.java:780)
 
  at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected (MenuBuilder.java:822)
 
  at android.support.v7.view.menu.SubMenuBuilder.dispatchMenuItemSelected (SubMenuBuilder.java:89)
 
  at android.support.v7.view.menu.MenuItemImpl.invoke (MenuItemImpl.java:171)
 
  at android.support.v7.view.menu.MenuBuilder.performItemAction (MenuBuilder.java:973)
 
  at android.support.v7.view.menu.MenuPopup.onItemClick (MenuPopup.java:127)
 
  at android.widget.AdapterView.performItemClick (AdapterView.java:318)
 
  at android.widget.AbsListView.performItemClick (AbsListView.java:1165)
 
  at android.widget.AbsListView$PerformClick.run (AbsListView.java:3134)
 
  at android.widget.AbsListView$3.run (AbsListView.java:4049)
 
  at android.os.Handler.handleCallback (Handler.java:789)
 
  at android.os.Handler.dispatchMessage (Handler.java:98)
 
  at android.os.Looper.loop (Looper.java:164)
 
  at android.app.ActivityThread.main (ActivityThread.java:6541)
 
  at java.lang.reflect.Method.invoke (Native Method)
 
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
 
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:767)
```

### PR DESCRIPTION
**Pull request by cham3333**
App was crashing because from api 24 google has made it compulsory to use FileProvider. We cannot expose file uri anymore. I have changed Uri.fromFile to FileProvider. Please let me know if any change is required in my code. Thank you.

### CODE REVIEW

**Comment by gsantner** [comment]
thanks! Is this backward compatible / does it work on e.g. API16 too?

File: app/src/main/java/net/gsantner/markor/activity/PreviewActivity.java [hunk 1]
```diff
@@ -200,11 +201,21 @@ private void shareImage() {
...
             File image = new File(getExternalCacheDir(), _note.getName() + ".png");
             if (saveBitmap(bitmap, image)) {
-                shareStream(Uri.fromFile(image), "image/png");
+                Uri imageUri = FileProvider.getUriForFile(PreviewActivity.this,
+                        Constants.FILE_PROVIDER_AUTHORITIES,
+                        image);
+                shareStream(imageUri, "image/png");
             }
         }
     }
```
Comment (gsantner) [inline app/src/main/java/net/gsantner/markor/activity/PreviewActivity.java]: I would convert this to take parameter (File, MimeType) and call that for image with imagpath and image/png, and for the note with _note and text/plain

**Comment by cham3333** [comment]
Yes, it runs on older devices. The FileProvider class is part of the v4 Support Library.

File: app/src/main/java/net/gsantner/markor/activity/PreviewActivity.java (hunk 1 above)
Comment (cham3333) [reply app/src/main/java/net/gsantner/markor/activity/PreviewActivity.java]: Thanks. I will do the required changes.

Comment (gsantner) [reply app/src/main/java/net/gsantner/markor/activity/PreviewActivity.java]: Dont feel like you must do things, this project is community work after all 😉

Comment (cham3333) [reply app/src/main/java/net/gsantner/markor/activity/PreviewActivity.java]: haha. okay. You were right actually. It does make code cleaner. I have changed the method signatures. Have a look at it and merge it if it looks alright to you.

Comment (gsantner) [reply app/src/main/java/net/gsantner/markor/activity/PreviewActivity.java]: thx, merging.

Here are more hacktober issues of my projects if you want more:

https://github.com/search?&q=label%3Ahacktoberfest+user%3Agsantner

Maybe look especially into MemeTastic.MemeCreateActivity - if the "share" file is done correctly. It may also use the old method with exposing uri

**Comment by gsantner** [comment]
:tada:

File: app/src/main/java/net/gsantner/markor/activity/PreviewActivity.java (hunk 1 above)
Comment (cham3333) [reply app/src/main/java/net/gsantner/markor/activity/PreviewActivity.java]: Great! Yea I will look into them too.
